use_frameworks!

def default_pods
  pod 'ScreenOrientationManager', :path => '../'
end

target 'ScreenOrientationManager_Example' do
  default_pods
end

target 'ScreenOrientationManager_Tests' do
  default_pods
end